begin
  Post.create!(
    title: "Getting started with RVM, Homebrew, and zSh on OS X Mountain Lion",
            created_at: "August 01, 2012",
            markdown_body: "#__August 1, 2012__\n\n##Step 1: \nInstall xCode 4.4+ from Apple or your desired source and install cmd line tools.\n\nIf upgrading from a previous version of OS X, update the location of xCode:\n\n{% highlight bash %}\nsudo xcode-select -switch /Applications/Xcode.app/Contents/Developer\n{% endhighlight %}\n\n##Step 2: \nInstall XQuartz (not included in xCode or 10.8 anymore): \n\n\u003chttp://xquartz.macosforge.org/trac/wiki/X112.7.2\u003e\n\nThis will require you to logout and re-login in after install.\n\n##Step 3: \nInstall Homebrew into /usr/local:\n\nIt has been recommended to create the folder '/usr/local/Cellar' before hand, due to some bug on homebrew. Once you've done that:\n\n{% highlight bash %}\nruby -e '$(curl -fsSkL raw.github.com/mxcl/homebrew/go)'\n{% endhighlight %}\n\n_or_\n\n{% highlight bash %}\nruby \u003c(curl -fsSkL raw.github.com/mxcl/homebrew/go)\n{% endhighlight %}\n\nNow make sure you can write into /usr/local/Cellar where homebrew installs everything, so:\n\n{% highlight bash %}\nchown -R $USER /usr/local/Cellar\n{% endhighlight %}\n\n##Step 4: \nInstall RVM from home directory:\n\n{% highlight bash %}\ncurl -L https://get.rvm.io | bash -s stable\n{% endhighlight %}\n\nThen reload your shell with RVM.\n\n{% highlight bash %}\nsource /Users/\u003cuser_name\u003e/.rvm/scripts/rvm\n{% endhighlight %}\n\nTo see the requirements for your system:\n\n{% highlight bash %}\nrvm requirements\n{% endhighlight %}\n\nOn my fresh OS X 10.8 install I was instructed by RVM to do the following:\n\n{% highlight bash %}\nbrew update\n{% endhighlight %}\n\n{% highlight bash %}\nbrew tap homebrew/dupes\n{% endhighlight %}\n\n{% highlight bash %}\nbrew install autoconf automake apple-gcc42\n{% endhighlight %}\n\n{% highlight bash %}\nrvm pkg install openssl\n{% endhighlight %}\n\n##Step 5: \nInstall Ruby 1.9.3:\n\n{% highlight bash %}\nrvm install 1.9.3\n{% endhighlight %}\n\nIf you've followed the setps above then you should be fine to continue from here.\n\n##Step 6: \nSet Ruby 1.9.3 as the system default:\n\n{% highlight bash %}\nrvm use ruby-1.9.3\n{% endhighlight %}\n\n##Step 7: \nChanging the default shell in OS X (bash) to zShell (zsh)\n\n{% highlight bash %}\nbrew install zsh\n{% endhighlight %}\n\nVerify your path at this point, though it should be /usr/local/bin/zsh if you followed the instructions above on a clean Mountain Lion install.\n\nNow run: \n\n{% highlight bash %}\nchsh\n{% endhighlight %}\n\nAfter you'll be asked to enter your root password which will then open the default editor within your shell window.\n\nOnce inside edit the line labeled 'Shell' to match your path to zsh\n\n{% highlight bash %}\nOpen Directory: /Local/Default\n\nShell: /bin/zsh\n\nFull Name: MasterControl\n\nOffice Location:\n\nOffice Phone:\n\nHome Phone:\n{% endhighlight %}\n\nSave the file and reopen your terminal.",
            markdown_excerpt: "#__August 1, 2012__ ##Step 1: Install xCode 4.4+ from Apple or your desired source and install cmd line tools. If upgrading from a previous version"
  )
  puts "Imported #{"Getting started with RVM, Homebrew, and zSh on OS X Mountain Lion"}"
rescue ActiveRecord::RecordInvalid => e
  puts "Error importing 01-08-2012-RVM_OSX.markdown: #{e.message}"
rescue => e
  puts "Unexpected error importing 01-08-2012-RVM_OSX.markdown: #{e.message}"
end
