production:
  fetch_feeds:
    class: FetchFeedsJob
    queue: default
    args: []
    schedule: every hour
  prune_feeds:
    class: PruneOldFeedPostsJob
    queue: default
    args: []
    schedule: every day